version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/filiicodex"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/filiicodex/rootfs/opt/filiicodex"
  schedule:
    interval: daily
